blogsys/urls.py
# -*-coding:utf-8-*-
"""blogsys URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from blog import views
from django.views.static import serve
from blog.upload import upload_image

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^all/(?P<type_id>\d+)', views.index),
    url(r'^all', views.index),
    url(r'^$', views.index),
    url(r'^produce_code', views.produce_code),

    url(r'^login', views.login),
    url(r'^logout', views.logout),
    url(r'^reg', views.reg),
    url(r'^uploads/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT, }),
    #富文本编辑器图片上传
    url(r'^admin/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
]

blog/models.py
# -*- coding:utf-8 -*-
from django.db import models


class UserInfo(models.Model):
    """
    用户表
    """
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    nickname = models.CharField(verbose_name='昵称', max_length=32, null=True, blank=True)
    email = models.EmailField(verbose_name='邮箱', unique=True, null=True, blank=True)
    avatar = models.ImageField(verbose_name='头像', null=True, blank=True, upload_to='avatar')

    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    fans = models.ManyToManyField(verbose_name='粉丝们',
                                  to='UserInfo',
                                  through='UserFans',
                                  related_name='f',
                                  through_fields=('user', 'follower'))

    '''print的时候显示'''
    def __str__(self):
        return self.username

    class Meta:
        verbose_name = '用户表'  # 这个让后台显示我们自定的表名
        verbose_name_plural = verbose_name  # 因为是外国人设计的，如果不写这个会在名字后面跟一个s
        ordering = ['-nid']



class UserFans(models.Model):
    """
    互粉关系表
    """
    user = models.ForeignKey(verbose_name='博主', to='UserInfo', to_field='nid',
                             on_delete=models.CASCADE,
                             related_name='users')
    follower = models.ForeignKey(verbose_name='粉丝',to='UserInfo', to_field='nid',
                                 on_delete=models.CASCADE,
                                 related_name='followers')

    # 联合唯一
    class Meta:
        verbose_name = '互粉关系表'  # 这个让后台显示我们自定的表名
        verbose_name_plural = verbose_name  # 因为是外国人设计的，如果不写这个会在名字后面跟一个s
        ordering = ['-id']
        unique_together = [
            ('user', 'follower'),
        ]


class Category(models.Model):
    """
    文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=128)
    index = models.IntegerField(verbose_name='分类排序', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '文章分类表'  # 这个让后台显示我们自定的表名
        verbose_name_plural = verbose_name  # 因为是外国人设计的，如果不写这个会在名字后面跟一个s
        ordering = ['-nid']


class UpDown(models.Model):
    """
    文章顶或踩
    """
    article = models.ForeignKey(verbose_name='文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='赞或踩用户', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    up = models.BooleanField(verbose_name='是否赞')

    class Meta:
        verbose_name = '文章顶或踩'  # 这个让后台显示我们自定的表名
        verbose_name_plural = verbose_name  # 因为是外国人设计的，如果不写这个会在名字后面跟一个s
        ordering = ['-id']
        unique_together = [
            ('article', 'user'),
        ]

class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复评论', to='self', related_name='back', null=True, on_delete=models.CASCADE)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论表'  # 这个让后台显示我们自定的表名
        verbose_name_plural = verbose_name  # 因为是外国人设计的，如果不写这个会在名字后面跟一个s
        ordering = ['-nid']

class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '标签'  # 这个让后台显示我们自定的表名
        verbose_name_plural = verbose_name  # 因为是外国人设计的，如果不写这个会在名字后面跟一个s
        ordering = ['-nid']


class Article(models.Model):
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题', max_length=128)
    content = models.TextField(verbose_name='文章内容', blank=True, null=True)
    summary = models.CharField(verbose_name='文章简介', max_length=255)
    read_count = models.IntegerField(verbose_name='阅读次数', default=0)
    comment_count = models.IntegerField(verbose_name='评论次数', default=0)
    #up_count = models.IntegerField(default=0)
    #down_count = models.IntegerField(default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    category = models.ForeignKey(verbose_name='文章类型', to='Category', to_field='nid',
                                 null=True, on_delete=models.CASCADE)

    type_choices = [
        (1, "Python"),
        (2, "Linux"),
        (3, "OpenStack"),
        (4, "GoLang"),
    ]
    article_type_id = models.IntegerField(choices=type_choices, default=None)

    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    class Meta:
        verbose_name = '文章'  # 这个让后台显示我们自定的表名
        verbose_name_plural = verbose_name  # 因为是外国人设计的，如果不写这个会在名字后面跟一个s
        ordering = ['-nid']


class Article2Tag(models.Model):
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '第二标签'  # 这个让后台显示我们自定的表名
        verbose_name_plural = verbose_name  # 因为是外国人设计的，如果不写这个会在名字后面跟一个s
        unique_together = [
            ('article', 'tag'),
        ]

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/mycss/commons.css">
</head>
<body>


<nav class="navbar navbar-default no-radius">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="#">老子的技术论坛</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if type_id %}
                    <li><a href="/all">All <span class="sr-only">(current)</span></a></li>
                {% else %}
                    <li class="active"><a href="/all">All <span class="sr-only">(current)</span></a></li>
                {% endif %}

                {% for item in type_choices_list %}
                    {% if item.0 == type_id %}
                        <li class="active"><a href="/all/{{ item.0 }}">{{ item.1 }}</a></li>
                    {% else %}
                        <li><a href="/all/{{ item.0 }}">{{ item.1 }}</a></li>
                    {% endif %}

                {% endfor %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.session.user %}
                    <li><a href="#">hello {{ request.session.user }}</a></li>
                    <li><a href="/logout">注销</a></li>
                {% else %}
                    <li><a href="/login">登录</a></li>
                    <li><a href="/reg">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <div class="col-md-8">
        <div class="article-list">

            <div class="article-item">
                <div class="art-head"><a href="#">php是世界上最好的语言</a></div>
                <div class="art-body clearfix">
                    <a href="" class="left"><img src="/static/avatar/cat.jpeg" alt=""></a>
                    作为阿里巴巴A100首批战略合作伙伴，红蜻蜓、雅戈尔等与阿里云合作建设数据中台、智慧门店等，在今年天猫双11中创下佳绩。红蜻蜓全渠道单品牌销售额突破3.8亿，位列鞋品牌榜第四。雅戈尔全网销售额1.24亿，同比增长88.8%。
                </div>
                <div class="art-foot">
                    <a href="">peter</a>
                    <a href="">点赞(2)</a>
                </div>
            </div>

            {% for article in pg_art_list %}
                <div class="article-item">
                    <div class="art-head"><a href="#">{{ article.title }}</a></div>
                    <div class="art-body clearfix">
                        <a href="" class="left"><img src="{{ article.blog.user.avatar }}" alt=""></a>
                        {{ article.summary }}
                    </div>
                    <div class="art-foot">
                        <a href="">{{ article.blog.user.username }}</a>
                        <a href="">{{ article.up_count }}</a>
                    </div>
                </div>
            {% endfor %}


        </div>
    </div>

    <div class="col-md-4">

        <div class="panel panel-primary">
            <div class="panel-body">
                Panel content
            </div>
            <div class="panel-body">
                Panel content
            </div>
            <div class="panel-body">
                Panel content
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-body">
                Panel content
            </div>
            <div class="panel-body">
                Panel content
            </div>
            <div class="panel-body">
                Panel content
            </div>
        </div>
    </div>
</div>


<div class="container pg">
    <div class="col-md-6 col-md-offset-3">
        <nav aria-label="Page navigation">
            <ul class="pagination">

                {% if pg_art_list.has_previous %}
                    <li><a href="?pg={{ pg_art_list.previous_page_number }}">上一页</a></li>
                {% else %}
                    <li class="disabled"><a>上一页</a></li>
                {% endif %}


                {% for page in page_list %}
                    <li><a href="?pg={{ page }}">{{ page }}</a></li>
                {% endfor %}

                {% if pg_art_list.has_next %}
                    <li><a href="?pg={{ pg_art_list.next_page_number }}">下一页</a></li>
                {% else %}
                    <li class="disabled"><a>下一页</a></li>
                {% endif %}

            </ul>
        </nav>
    </div>
</div>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/mycss/commons.css">
    <script src="/static/jquery-3.4.1.min.js"></script>
</head>
<body>
<div class="container log">
    <div class="col-md-6 col-md-offset-3">
        <form class="form-horizontal" method="post" >
            {% csrf_token %}
            <div class="form-group">
                <label for="id_user" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    {{ login_form.user }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_password" class="col-sm-2 control-label">密码</label>
                <div class="col-sm-10">
                    {{ login_form.password }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_code" class="col-sm-2 control-label">验证码</label>
                <div class="col-sm-5">
                    {{ login_form.code }}
                </div>
                <img src="/produce_code" alt="auth_code" class="auth_code">
                 <span>{{ err.code }}</span>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" class="btn btn-default" value="登录">
                    <span style="color: red;margin-left: 20px">{{ err.password }}</span>
                </div>
            </div>
        </form>
    </div>
</div>

<script>

    $('.auth_code').click(function () {
        $(this)[0].src += '?'
    })

</script>
</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/mycss/commons.css">
    <script src="/static/jquery-3.4.1.min.js"></script>
</head>
<body>
<div class="container log">
    <div class="col-md-6 col-md-offset-3">
        <form class="form-horizontal" method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_user" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    {{ reg_form.user }} <span id="user_error"></span>
                </div>
            </div>

            <div class="form-group">
                <label for="id_password" class="col-sm-2 control-label">密码</label>
                <div class="col-sm-10">
                    {{ reg_form.password }} <span></span>
                </div>
            </div>

            <div class="form-group">
                <label for="id_repeat_password" class="col-sm-2 control-label">重复密码</label>
                <div class="col-sm-10">
                    {{ reg_form.repeat_password }} <span id="repeat_error"></span>
                </div>
            </div>

            <div class="form-group">
                <label for="id_email" class="col-sm-2 control-label">邮箱</label>
                <div class="col-sm-10">
                    {{ reg_form.email }} <span></span>
                </div>
            </div>

            <div class="form-group">
                <label for="avatar" class="col-sm-2 control-label">头像</label>
                <div class="col-sm-10">
                    <img src="/static/avatar/default.jpg" id="default_img">
                    <input type="file" id="avatar">
                </div>
            </div>

            <div class="form-group" style="margin-top: 50px">
                <label for="id_code" class="col-sm-2 control-label">验证码</label>
                <div class="col-sm-5">
                    {{ reg_form.code }} <span></span>
                </div>
                <img src="/produce_code" alt="auth_code" class="auth_code">
                <span>{{ err.code }}</span>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="button" class="btn btn-default register" value="注册">
                    <span class="error"></span>
                </div>
            </div>

        </form>
    </div>
</div>

<script>

    $('.auth_code').click(function () {
        $(this)[0].src += '?'
    });

    $('.register').click(function () {
        var user = $('#id_user').val();
        var password = $('#id_password').val();
        var repeat_password = $('#id_repeat_password').val();
        var email = $('#id_email').val();
        var avatar_obj = $('#avatar')[0].files[0];
        var code = $('#id_code').val();
        var csrf = $('[name="csrfmiddlewaretoken"]').val();

        var formdata = new FormData();
        formdata.append('user', user);
        formdata.append('password', password);
        formdata.append('repeat_password', repeat_password);
        formdata.append('email', email);
        formdata.append('avatar', avatar_obj);
        formdata.append('code', code);
        formdata.append('csrfmiddlewaretoken', csrf);

        $.ajax({
            url: '/reg',
            type: 'POST',
            data: formdata,
            contentType: false,
            processData: false,
            success: function (data) {
                data = JSON.parse(data);
                if (data.flag) {
                    location.href = '/login'
                } else {
                    if (data.user_error) {
                        $('#user_error').text(data.user_error).css('color', 'red')
                    } else {
                        error = data.error;
                        for (var i in error) {
                            if (i == '__all__') {
                                $('#repeat_error').text(error[i]).css('color', 'red')
                            } else {
                                $('#id_' + i).next().text(error[i]).css('color', 'red')
                            }
                        }
                    }
                }

            }
        })
    });

    //头像预览
    $('#avatar').change(function () {

        var reader = new FileReader();
        var upload_file = $(this)[0].files[0];
        reader.readAsDataURL(upload_file);

        reader.onload = function () {
            $('#default_img')[0].src = this.result;
        }
    })
</script>
</body>
</html>